# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: 'Varnish | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'varnish'
    - 'varnish-package'
    - 'varnish-configure'
    - 'varnish-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Varnish | Debian | Include distribution-specific variables.'
  include_vars: 'Debian-Xenial.yml'
  when: '{{ ansible_os_family == "Debian" and ansible_distribution_release == "xenial" }}'
  tags:
    - 'varnish'
    - 'varnish-package'
    - 'varnish-configure'
    - 'varnish-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Varnish | RedHat | Include distribution-specific variables.'
  include_vars: 'RedHat-7.yml'
  when: '{{ ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" }}'
  tags:
    - 'varnish'
    - 'varnish-package'
    - 'varnish-configure'
    - 'varnish-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Varnish | Define Varnish service name.'
  set_fact:
    varnish_service_name: '{{ varnish_default_service_name }}'
  when: '{{ not varnish_service_name }}'
  tags:
    - 'varnish'
    - 'varnish-package'
    - 'varnish-configure'
    - 'varnish-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Varnish | Define Varnish packages.'
  set_fact:
    varnish_packages: '{{ varnish_default_packages }}'
  when: '{{ not varnish_packages }}'
  tags:
    - 'varnish'
    - 'varnish-package'
    - 'varnish-configure'
    - 'varnish-service'
    - 'package'
    - 'configure'
    - 'service'

- include: 'package.yml'
  tags:
    - 'varnish'
    - 'varnish-package'
    - 'package'

- include: 'configure.yml'
  tags:
    - 'varnish'
    - 'varnish-configure'
    - 'configure'

- include: 'service.yml'
  tags:
    - 'varnish'
    - 'varnish-service'
    - 'service'